-- AlterTable
ALTER TABLE "Meal"
ALTER COLUMN "calories" TYPE DOUBLE PRECISION USING "calories"::DOUBLE PRECISION,
ALTER COLUMN "protein" TYPE DOUBLE PRECISION USING "protein"::DOUBLE PRECISION,
ALTER COLUMN "carbs" TYPE DOUBLE PRECISION USING "carbs"::DOUBLE PRECISION,
ALTER COLUMN "fat" TYPE DOUBLE PRECISION USING "fat"::DOUBLE PRECISION;
